services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    ports:
      - "8080:8080"

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    command: sh -c "sleep 5 && node index.js"
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
    restart: always
